"""JSONL entry types for session transcript persistence.

Each conversation turn produces one or more entries appended to a
``.jsonl`` file.  Entries form a linked list via ``uuid`` /
``parent_uuid`` pointers, enabling chain reconstruction on resume.

Entry types mirror the conversation lifecycle:

- **UserMessageEntry** — written *before* the LLM API call so user
  input survives a daemon crash.
- **AssistantMessageEntry** — written after a complete LLM turn
  (text + tool-use blocks + usage stats).
- **ToolCallEntry** — one per tool invocation, written after execution
  completes (call params + result together).
- **CompactBoundaryEntry** — marks where context compression occurred
  (Phase 4.2).
- **SessionMetaEntry** — key/value metadata changes (title, tag, …).
"""

from __future__ import annotations

import uuid as _uuid
from datetime import datetime, timezone
from typing import Annotated, Any, Literal

from pydantic import BaseModel, Field


def _new_uuid() -> str:
    """Generate a random UUID string."""
    return str(_uuid.uuid4())


def _now_iso() -> str:
    """Current UTC time as ISO-8601 string."""
    return datetime.now(timezone.utc).isoformat()


# ------------------------------------------------------------------
# Base
# ------------------------------------------------------------------


class BaseEntry(BaseModel):
    """Common fields shared by every JSONL entry.

    Attributes:
        uuid: Unique identifier for this entry.
        parent_uuid: UUID of the preceding entry (``None`` for the
            first entry in a session).  Used to rebuild the
            conversation chain on resume.
        timestamp: ISO-8601 UTC timestamp of when the entry was
            created.
        type: Discriminator field — overridden by each subclass.
    """

    uuid: str = Field(default_factory=_new_uuid)
    parent_uuid: str | None = None
    timestamp: str = Field(default_factory=_now_iso)
    type: str


# ------------------------------------------------------------------
# Concrete entry types
# ------------------------------------------------------------------


class UserMessageEntry(BaseEntry):
    """User input — written to disk before the LLM API call.

    Persisting eagerly ensures that a daemon crash after the user
    presses Enter but before the LLM responds does not lose the
    message.

    Attributes:
        content: The raw text the user typed.
    """

    type: Literal["user_message"] = "user_message"
    content: str


class AssistantMessageEntry(BaseEntry):
    """Complete LLM response for one turn.

    Stored after ``StreamEnd`` is received.  The ``content`` list
    mirrors :class:`~daemon.providers.base.Message.content` and can
    contain text blocks and/or tool-use blocks.

    Attributes:
        content: Serialised ``MessageContent`` items (dicts).
        usage: Token counts — ``{"input_tokens": N, "output_tokens": N}``.
    """

    type: Literal["assistant_message"] = "assistant_message"
    content: list[dict[str, Any]]
    usage: dict[str, int] = Field(default_factory=lambda: {"input_tokens": 0, "output_tokens": 0})


class ToolCallEntry(BaseEntry):
    """A single tool invocation and its result.

    Call parameters and execution output are stored together in one
    entry to keep the chain simple.  Phase 5 may split this for
    parallel tool-call support.

    Attributes:
        tool_call_id: Provider-assigned call identifier.
        tool_name: Registered tool name (e.g. ``"bash"``).
        arguments: Arguments passed to the tool.
        output: Tool execution output (stdout / result text).
        is_error: Whether the tool reported an error.
        synthetic: ``True`` when the entry was generated by the
            orchestrator's cancellation-finalizer (tool was
            interrupted, not actually invoked or not allowed to
            finish). Default ``False`` preserves JSONL backward
            compatibility.
        cancel_phase: Phase at which cancellation hit — one of
            ``permission_wait`` / ``pre_hooks`` / ``executing``.
            ``None`` when ``synthetic`` is ``False``. Persisted
            separately from ``output`` so audit tooling can filter
            without parsing the text.
    """

    type: Literal["tool_call"] = "tool_call"
    tool_call_id: str
    tool_name: str
    arguments: dict[str, Any]
    output: str
    is_error: bool = False
    synthetic: bool = False
    cancel_phase: str | None = None
    image_parts: list[dict[str, Any]] | None = None
    """Serialised :class:`ImageContent` blocks produced by the tool.

    JSONL-friendly form: each dict carries ``media_type`` +
    ``source_sha256`` but an empty ``data_base64`` — the actual image
    bytes live in ``~/.mustang/cache/images/{sha}.{ext}``.  ``None``
    preserves backward compatibility for pre-5.6 transcripts.
    """


class CompactBoundaryEntry(BaseEntry):
    """Marker for context compression (Phase 4.2).

    Inserted when old messages are summarised and discarded to free
    context window space.

    Attributes:
        summary: LLM-generated summary of the compacted messages.
        preserved_count: Number of messages retained after compaction.
    """

    type: Literal["compact_boundary"] = "compact_boundary"
    summary: str
    preserved_count: int = 0


class SessionMetaEntry(BaseEntry):
    """Session metadata change.

    Captures key/value updates such as a user-assigned title or tag.

    Attributes:
        key: Metadata field name (e.g. ``"title"``, ``"tag"``).
        value: New value for the field.
    """

    type: Literal["session_meta"] = "session_meta"
    key: str
    value: str


# ------------------------------------------------------------------
# Discriminated union
# ------------------------------------------------------------------

Entry = Annotated[
    UserMessageEntry
    | AssistantMessageEntry
    | ToolCallEntry
    | CompactBoundaryEntry
    | SessionMetaEntry,
    Field(discriminator="type"),
]
"""Union of all JSONL entry types, discriminated by the ``type`` field."""
