"""Pydantic models for the per-session ``.meta.json`` file.

Separated from :mod:`daemon.sessions.storage` (which owns the
:class:`TranscriptWriter` I/O logic) so the metadata schema can be
imported without pulling JSONL-reader machinery.  Both models are
re-exported from ``daemon.sessions.storage`` for backward
compatibility with existing import sites.
"""

from __future__ import annotations

from datetime import datetime, timezone

from pydantic import BaseModel, Field


class ModelUsage(BaseModel):
    """Token usage breakdown for a single model within a session.

    Attributes:
        input_tokens: Total input tokens consumed by this model.
        output_tokens: Total output tokens generated by this model.
        cache_creation_tokens: Tokens used to create prompt cache entries.
        cache_read_tokens: Tokens served from prompt cache.
    """

    input_tokens: int = 0
    output_tokens: int = 0
    cache_creation_tokens: int = 0
    cache_read_tokens: int = 0


class SessionMeta(BaseModel):
    """Persisted metadata for a session.

    Stored as ``{session_id}.meta.json`` alongside the transcript.
    Updated in-memory during the session and flushed to disk on
    mutation.

    Attributes:
        session_id: Unique session identifier.
        created_at: ISO-8601 UTC timestamp.
        updated_at: ISO-8601 UTC timestamp (refreshed on each write).
        cwd: Working directory when the session was created.
        model: LLM model ID used in this session at creation time.
            Does not change if the user switches model mid-session;
            see :attr:`model_usage` for per-model breakdown.
        provider: Provider name at session creation.
        title: Optional user-assigned session title.
        total_input_tokens: Cumulative input token count across all models.
        total_output_tokens: Cumulative output token count across all models.
        model_usage: Per-model token breakdown — populated when the
            user switches between models via ``/model switch``.
        message_count: Number of transcript entries written.
    """

    session_id: str
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    updated_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    cwd: str = ""
    model: str = ""
    provider: str = ""
    title: str | None = None
    total_input_tokens: int = 0
    total_output_tokens: int = 0
    model_usage: dict[str, ModelUsage] = Field(default_factory=dict)
    message_count: int = 0


__all__ = ["ModelUsage", "SessionMeta"]
