"""The immutable identity descriptor produced by ``ConnectionAuthenticator``.

Design invariants (see ``docs/kernel/subsystems/connection_authenticator.md``):

1. **Immutable** — frozen dataclass.  Once authentication succeeds
   the identity is locked for the lifetime of the transport
   connection.  A client that wants to swap credentials must
   disconnect and re-handshake.
2. **Never stores the raw credential** — only the *type* of
   credential used.  The plaintext token / password is consumed by
   ``ConnectionAuthenticator.authenticate`` and dropped before this
   object is constructed, so even a log of ``repr(ctx)`` cannot leak it.
3. **Minimal field set** — on purpose.  Session id, client info,
   permissions, and expiry all live in layers above (protocol /
   session) or do not exist in this kernel's design at all.  Keeping
   ``AuthContext`` narrow means new connection-level state is added
   to ``ConnectionContext`` in the protocol layer rather than
   polluting the identity descriptor.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Literal


@dataclass(frozen=True)
class AuthContext:
    """Authenticated identity bound to a single transport connection.

    Produced by
    :meth:`kernel.connection_auth.ConnectionAuthenticator.authenticate` on
    success.  Flows from transport → protocol → session as a
    read-only descriptor of "who is on the other end of this
    connection".
    """

    connection_id: str
    """``uuid4().hex`` generated by the transport layer when the
    socket is accepted.  Used to correlate log entries, audit
    records, and broadcast event streams back to the originating
    connection.  ConnectionAuthenticator does **not** generate this itself —
    transports must pass their own id in so a single connection
    carries the same id across transport / protocol / session logs.
    """

    credential_type: Literal["token", "password"]
    """Which credential kind was used to authenticate.  Under this
    kernel's loopback-only architecture this is the only reliable
    signal for "local vs forwarded-from-remote" — see :attr:`is_local`.
    """

    remote_addr: str
    """``host:port`` of the socket's remote end, as seen by the
    transport layer.  Because kernel only binds ``127.0.0.1`` this
    is almost always ``127.0.0.1:<ephemeral>`` (a local client or a
    local reverse proxy forwarding a remote request).  Retained for
    diagnostic logging only — never use it for authorization
    decisions.
    """

    authenticated_at: datetime
    """UTC timestamp of successful verification."""

    @property
    def is_local(self) -> bool:
        """``True`` iff the credential is known to originate locally.

        A token credential can only be obtained by reading
        ``~/.mustang/state/auth_token`` on the same machine, so
        ``token → definitely local``.  A password credential may
        have been supplied by a local client or forwarded through a
        reverse proxy from the outside world; we cannot distinguish
        those cases (see the ``remote_addr`` caveat above) so we
        conservatively report non-local.
        """
        return self.credential_type == "token"
