"""Tool lifecycle events emitted by the Orchestrator.

Tool events are the kernel-internal shape.  The ACP mapper projects them into
client protocol updates, so these dataclasses can preserve Mustang-specific
fields such as semantic ``ToolKind`` without leaking that enum to ACP.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from kernel.orchestrator.tool_kinds import ToolKind
    from kernel.protocol.interfaces.contracts.content_block import ContentBlock


@dataclass(frozen=True)
class ToolCallStart:
    """Emitted once when a tool call begins.

    ``raw_input`` is capped before construction by the executor; it is debug
    metadata, not an authoritative copy of the tool input.
    """

    id: str
    # User-facing title generated by the Tool implementation, not the raw name.
    title: str
    kind: ToolKind
    raw_input: str | None = None


@dataclass(frozen=True)
class ToolCallProgress:
    """Progress emitted while a tool is running.

    Progress is optional and may contain passthrough events from tools that
    already know the client-facing representation.
    """

    id: str
    content: list[ContentBlock]


@dataclass(frozen=True)
class ToolCallResult:
    """Emitted once when a tool call completes successfully.

    The content mirrors the visible tool result.  The LLM-facing result may be
    separately budgeted before it is appended to conversation history.
    """

    id: str
    content: list[ContentBlock]


@dataclass(frozen=True)
class ToolCallError:
    """Emitted when a tool call fails or is denied.

    Authorization denials are represented as errors because the LLM must still
    receive a ``tool_result`` block for every ``tool_use`` it emitted.
    """

    id: str
    error: str


@dataclass(frozen=True)
class ToolCallDiff:
    """Optional companion event for file-editing tools.

    This companion shape keeps diffs out of the generic result payload, allowing
    clients to render file edits with purpose-built UI affordances.
    """

    id: str
    path: str
    old_text: str | None
    new_text: str


@dataclass(frozen=True)
class ToolCallLocations:
    """Optional companion event for navigable source locations.

    Location dictionaries stay loose because different tools can expose file,
    symbol, or search-hit coordinates without changing the event union.
    """

    id: str
    locations: list[dict[str, Any]]
